apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: metastore-mysql
  name: metastore-mysql
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
