apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: metastore
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: hive-metastore
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: hive-metastore-0.1.0
  name: metastore-hive-metastore
spec:
  ports:
  - name: metastore
    port: 9083
    protocol: TCP
    targetPort: metastore
  selector:
    app.kubernetes.io/instance: metastore
    app.kubernetes.io/name: hive-metastore
  type: ClusterIP
