apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metastore-mysql
  name: metastore-mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: metastore-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: metastore-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: metastore-mysql
        - name: MYSQL_USER
          value: hive
        - name: MYSQL_DATABASE
          value: metastore
        image: mysql:5.7.28
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: metastore-mysql
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      initContainers:
      - command:
        - rm
        - -fr
        - /var/lib/mysql/lost+found
        image: busybox:1.29.3
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      serviceAccountName: default
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: metastore-mysql
