apiVersion: v1
kind: Service
metadata:
  labels:
    app: metastore-mysql
  name: metastore-mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: metastore-mysql
  type: ClusterIP
