apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-adapter
  name: monitoring-prometheus-adapter
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: prometheus-adapter
  type: ClusterIP
