apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    component: server
  name: monitoring-prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
