apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    component: alertmanager
  name: monitoring-prometheus-alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
