kind: pipeline
type: docker
name: Helm v2 Check

workspace:
  base: /build

steps:
  - name: build
    image: alpine/helm:2.16.1
    commands:
      - helm version --client
      - |
        mkdir -p /tmp/tools && \
        cd /tmp/tools && \
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz && tar xf kubeval-linux-amd64.tar.gz && mv kubeval /bin/kubeval
      - |
        cd /build
        for d in stable/*/; do
           echo "Validating chart $d"
           helm lint $d
           helm template $d | kubeval --strict --ignore-missing-schemas
         done

---
kind: pipeline
type: docker
name: Helm v3 Check

workspace:
  base: /build

steps:
  - name: build
    image: alpine/helm:3.0.0
    commands:
      - helm version --client
      - |
        mkdir -p /tmp/tools && \
        cd /tmp/tools && \
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz && tar xf kubeval-linux-amd64.tar.gz && mv kubeval /bin/kubeval
      - |
        cd /build
        for d in stable/*/; do
           echo "Validating chart $d"
           helm lint $d
           helm template $d | kubeval --strict --ignore-missing-schemas
         done
---
kind: pipeline
type: docker
name: Kustomize Test

workspace:
  base: /build

steps:
  - name: build
    image: alpine/helm:3.0.0
    commands:
      - apk update && apk add curl
      - |
        mkdir -p /tmp/tools && \
        cd /tmp/tools && \
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz && tar xf kubeval-linux-amd64.tar.gz && mv kubeval /bin/kubeval
      - |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
        chmod +x kubectl && mv kubectl /bin/kubectl
      - |
        cd /build
        for d in kustomize/*/*/; do
           echo "Kustomize Validating chart $d"
           kubectl kustomize $d | kubeval --strict --ignore-missing-schemas
         done

---
kind: pipeline
type: docker
name: Publish Charts

steps:
  - name: build
    image: alpine/helm:3.0.0
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - helm version --client
      - apk add --no-cache git
      - export REPOSITORY="https://hybrid-dev-qubole:$GITHUB_TOKEN@github.com/qubole/charts.git"
      - git config user.email hybrid-dev@qubole.com
      - git config user.name "CI Bot"
      - git remote set-url origin $REPOSITORY
      - git fetch --all
      - mkdir -p /tmp/helm
      - helm package stable/logging/ --destination /tmp/helm
      - helm package stable/monitoring/ --destination /tmp/helm
      - helm package stable/spark/ --destination /tmp/helm
      - helm package stable/security/ --destination /tmp/helm
      - helm package stable/hive-metastore/ --destination /tmp/helm
      - mkdir -p /tmp/charts/docs/ && mkdir -p /tmp/charts/stable/ && cp -a docs/. /tmp/charts/docs/ && cp README.md /tmp/ && cp -a stable/. /tmp/charts/stable/
      - git checkout gh-pages
      - rm -rf docs/ && rm -rf README.md && rm -rf stable
      - mkdir docs && mkdir stable
      - cp -a /tmp/charts/docs/. docs/ && cp /tmp/README.md . && cp -a /tmp/charts/stable/. stable/.
      - mv -f /tmp/helm/*.tgz .
      - helm repo index . --url https://qubole.github.io/charts
      - git add -A
      - git commit -m "Publish stable charts ${DRONE_COMMIT_BRANCH}"
      - git push origin gh-pages
      - echo "Published charts"


trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - Helm v2 Check
  - Helm v3 Check
  - Kustomize Test