bases:
  - ../base

patchesStrategicMerge:
  - efk-fluentd-pvc-patch.yaml

patchesJson6902:
  - target:
      kind: StatefulSet
      name: elasticsearch-master
      group: apps
      version: v1
    path: elasticsearch-master-statefulset-patch.json

