apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: spark
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.6.1
  name: spark-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
