apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: spark
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: spark-history-server
    helm.sh/chart: spark-history-server-1.1.1
  name: spark-spark-history-server
