{{- if .Values.fluentdForwarder.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "logging.fullname" . }}-forwarder
  labels:
    app: {{ template "logging.name" . }}
    chart: {{ template "logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "logging.fullname" .}}-forwarder
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "logging.fullname" . }}-forwarder
  apiGroup: rbac.authorization.k8s.io
{{- end -}}