{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "qubole.serviceAccountName" . }}
  labels:
{{ include "qubole.labels" . | indent 4 }}
{{- end -}}
