dependencies:
  - name: kibana
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: elasticsearch
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: fluentd
    version: 2.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluentd.enabled
  - name: hadoop
    version: 1.1.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: hadoop.enabled