{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "security.serviceAccountName" . }}
  labels:
{{ include "security.labels" . | indent 4 }}
{{- end -}}
