apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentd-forwarder
  labels:
    app.kubernetes.io/name: {{ include "logging.name" . }}
    helm.sh/chart: {{ include "logging.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "logging.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "logging.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.fluentdForwarder.serviceAccount.create }}
      serviceAccountName: {{ template "logging.fullname" . }}-forwarder
    {{- end}}
      containers:
        - name: {{ .Values.fluentdForwarder.containerName }}
          image: {{ .Values.fluentdForwarder.image.name}}:{{ .Values.fluentdForwarder.image.tag }}
          imagePullPolicy: {{ .Values.fluentdForwarder.image.pullPolicy }}
          env:
            - name:  FLUENT_FOWARD_HOST
              value: {{ quote .Values.fluentdForwarder.forward.host }}
            - name:  FLUENT_FOWARD_PORT
              value: {{ quote .Values.fluentdForwarder.forward.port }}
            {{- if .Values.fluentdForwarder.extraEnvVars }}
{{ toYaml .Values.fluentdForwarder.extraEnvVars | indent 10 }}
            {{- end }}
          resources:
{{ toYaml .Values.fluentdForwarder.resources | indent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
    {{- with .Values.fluentdForwarder.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end}}

