{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "logging.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.kibanaPath }}
            backend:
              serviceName: {{ .Release.Name }}-kibana
              servicePort: {{ .Values.kibana.service.port }}
  {{- end -}}