{{- if .Values.fluentd.sinks.s3 -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "logging.fullname" . }}-storage-s3
    labels:
        app: {{ template "logging.name" . }}
        chart: {{ template "logging.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
stringData:
    access_key_id: {{ required "AWS Access Key is required if S3 sink is enabled for fluentd" .Values.fluentd.secrets.s3.access_key_id }}
    secret_access_key: {{ required "AWS Secret Key is required if S3 sink is enabled for fluentd" .Values.fluentd.secrets.s3.secret_access_key }}
    bucket: {{ required "S3 bucket name is required if S3 sink is enabled for fluentd" .Values.fluentd.secrets.s3.bucket }}
    region: {{ required "S3 region is required if S3 sink is enabled for fluentd" .Values.fluentd.secrets.s3.region }}
{{- end -}}