apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: grafana
  name: metrics-grafana
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-grafana
subjects:
- kind: ServiceAccount
  name: metrics-grafana
  namespace: default
