apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    component: server
  name: metrics-prometheus-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-prometheus-server
subjects:
- kind: ServiceAccount
  name: metrics-prometheus-server
  namespace: default
