apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: kube-state-metrics
  name: metrics-prometheus-kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: kube-state-metrics
  template:
    metadata:
      labels:
        app: prometheus
        component: kube-state-metrics
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.6.0
        imagePullPolicy: IfNotPresent
        name: prometheus-kube-state-metrics
        ports:
        - containerPort: 8080
          name: metrics
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: metrics-prometheus-kube-state-metrics
