apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: grafana
  name: metrics-grafana
  namespace: default
rules:
- apiGroups:
  - extensions
  resourceNames:
  - metrics-grafana
  resources:
  - podsecuritypolicies
  verbs:
  - use
