apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: metrics-grafana
  namespace: default
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
