apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: grafana
  name: metrics-grafana-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-grafana-clusterrole
subjects:
- kind: ServiceAccount
  name: metrics-grafana
  namespace: default
