apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: fluentd
  name: efk-fluentd
rules:
- apiGroups:
  - extensions
  resourceNames:
  - efk-fluentd
  resources:
  - podsecuritypolicies
  verbs:
  - use
