{{- if index .Values "spark-history-server" "s3" "enableS3" }}
kind: Secret
apiVersion: v1
metadata:
    name: aws-secrets
data:
    aws-access-key: {{ required "AWS accessKeyID is required" ( (index .Values "spark-history-server" "s3" "accessKeyID") | b64enc) }}
    aws-secret-key: {{ required "AWS secretAccessKey is required" ( (index .Values "spark-history-server" "s3" "secretAccessKey") | b64enc) }}
type: Opaque
{{- end }}