apiVersion: v1
kind: Service
metadata:
  name: presto-superset
  namespace: presto
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 8088
  selector:
    app: superset
  type: ClusterIP
