apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: superset
  name: presto-superset
  namespace: presto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
