dependencies:
  - name: prometheus
    version: 9.3.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
  - name: prometheus-adapter
    version: 1.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-adapter.enabled
  - name: grafana
    version: 4.2.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled